$(document).ready(function(){
  $('#work1').mouseover(function(){
    $('#job1').show();
  }).mouseout(function(){
    $('#job1').hide()
  });
});
$(document).ready(function(){
  $('#work2').mouseover(function(){
    $('#job2').show();
  }).mouseout(function(){
    $('#job2').hide()
  });
});
$(document).ready(function(){
  $('#work3').mouseover(function(){
    $('#job3').show();
  }).mouseout(function(){
    $('#job3').hide()
  });
});
$(document).ready(function(){
  $('#work4').mouseover(function(){
    $('#job4').show();
  }).mouseout(function(){
    $('#job4').hide()
  });
});
$(document).ready(function(){
  $('#work5').mouseover(function(){
    $('#job5').show();
  }).mouseout(function(){
    $('#job5').hide()
  });
});
